# gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.java.installations.auto-download=false

# minecraft
minecraft_version=1.12.2

# forge
forge_gradle_version=6.0.+
forge_version=14.23.5.2860
mappings_channel=stable
mappings_version=39-1.12

# mod
mod_id=mod_lavacow
mod_name=Fish's Undead Rising
mod_version=1.5.3
mod_author=["Fish0016054", "IcarussOne", "ACGaming", "xJon"]
mod_description=Fill your world with all kinds of mobs, undead-related or not.

# dependencies
baubles_version=227083:2518667
mantle_version=74924:2713386
tinkers_construct_version=74072:2902483
constructs_armory_version=287683:3174535
jer_version=240630:2728585
jei_version=238222:5101347
rlcombat_version=711714:5940474
somanyenchantments_version=267035:6172363